  
name: Release version for Download

on:
  release:
    types: [released, edited]
    # types: [released, prereleased, published, edited, created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to Master branch
      uses: actions/checkout@main

    - name: Fetch Latest Release assets
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: "latest"
        file: "CloudLAN-win64.exe"

    - name: Move files to SOURCE_DIR
      run: pwd && ls && mkdir -p upload/cloudlan-releases/latest/ && mv CloudLAN-win64.exe upload/cloudlan-releases/latest/ && cd upload/cloudlan-releases/latest/ && ls

    - name: Upload Content to Digitalocean Spaces
      uses: kodertroop/do-space-sync-action@v1.0.1
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: './upload'
        SPACE_NAME: ${{ secrets.SPACE_NAME }}
        SPACE_REGION: ${{ secrets.SPACE_REGION}}
        SPACE_ACCESS_KEY_ID: ${{ secrets.SPACE_ACCESS_KEY_ID }}
        SPACE_SECRET_ACCESS_KEY: ${{ secrets.SPACE_SECRET_ACCESS_KEY }}
